# Maven

trigger: 
- main
pool:
  vmImage: ubuntu-latest
steps:
- task: JFrogMaven@1
  inputs:
    mavenPomFile: 'maven/My Maven Project With Spaces/pom.xml'
    goals: 'install'
    artifactoryResolverService: 'andrewr-jfrog'
    targetResolveReleaseRepo: 'farnoosh-libs-release'
    targetResolveSnapshotRepo: 'farnoosh-libs-snapshot'
    javaHomeOption: 'JDKVersion'
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java


