# azure-pipelines.yml

trigger:
- main  # Or your default branch

pool:
  vmImage: 'windows-latest' # Using a Windows agent

steps:
- checkout: self # Checks out your repository

- task: Maven@4 # Using Maven task version 4
  displayName: 'Maven Build with Space in POM Path'
- task: JFrogMaven@1
  inputs:
    mavenPomFile: 'mypathwithspace/pom.xml'
    goals: 'install'
    artifactoryResolverService: 'andrewr-jfrog'
    targetResolveReleaseRepo: 'farnoosh-libs-release'
    targetResolveSnapshotRepo: 'farnoosh-libs-snapshot'
    javaHomeOption: 'JDKVersion'